name: Deploy to AWS (Dev Environment) dev

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::166404899495:role/github-actions-role
        role-session-name: GitHubActions-dev

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config="key=dev/terraform.tfstate"

    - name: Terraform Import
      run: terraform import 'aws_s3_bucket.my_bucket' vizioi-mullman-example

    - name: Terraform Plan
      run: terraform plan -var-file="dev.tfvars"

    - name: Terraform Apply
      run: terraform apply -var-file="dev.tfvars" -auto-approve
